Make TensorFlow demo compatible with all the current EESSI repos and versions
EESSI/eessi-demo pull request #31
Opened 2024-02-07 15:03 UTC by laraPPr

2024-02-07 17:40 UTC, boegel commented
Maybe somewhat shorter & easier to digest:

```shell
if [[ ${EESSI_CVMFS_REPO} == "/cvmfs/software.eessi.io" ]] && [[ ${EESSI_VERSION} == "2023.06" ]]; then module load TensorFlow/2.13.0-foss-2023a
elif [[ ${EESSI_CVMFS_REPO} == "/cvmfs/pilot.eessi-hpc.org" ]] && [[ ${EESSI_PILOT_VERSION} == "2021.12" ]]; then module load TensorFlow/2.3.1-foss-2020a-Python-3.8.2
else echo "Don't know which TensorFlow module to load for ${EESSI_CVMFS_REPO}/versions/${EESSI_VERSION}${EESSI_PILOT_VERSION}" >&2; exit 1; fi
```

2024-02-08 10:42 UTC, boegel requested changes

2024-02-08 13:36 UTC, laraPPr commented on TensorFlow/run.sh
> +    fi
Changed it to the suggested change that you mention [here](https://github.com/EESSI/eessi-demo/pull/31#issuecomment-1932558286). So than unknown EESSI version should be covered. Or do you want something else?

2024-02-08 15:26 UTC, boegel commented on TensorFlow/run.sh
> +    fi
Indeed, the `else` takes care of unknown versions now

2024-02-08 15:35 UTC, boegel approved these changes

2024-02-08 15:35 UTC, merged

2024-02-08 15:35 UTC, boegel commented
Tested, works like a charm! :+1: